language: android

dist: trusty

jdk:
  - openjdk8

script:
  - ./gradlew clean build

before_install:
  # Install SDK license so Android Gradle plugin can install deps.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

after_success:
  - .buildscript/deploy_snapshot.sh

env:
  global:
    - secure: "D/huesY5hkq8JqwTmRUSePvagrJztRdQ7Bn58mSU2A5BugU90C/5QnejyyVtLDhEdn7DkndERsqEfr3v9nL3bQvsRj9SOa3tK7ylRt//0NuhDKKBYsZcf6A1xKp4FWrnzn79YoFrDHP5xWhYEEsyaVBYAI/box9MW3XS36fV9QmHHCSU5fPavUvV3g47U5gaEkXfM6ehhBosO3RR2MG1m8X4GU31FfEmk9HJFnUJ0JbrFjxAaZctciPgXXqYDqwfZHMJQMNvy9xgxh3pYRsrdFkdLrNk4NOI8SYggt4F8/eBu0kk22pQ97mt3cqZvUO43aKLAnbkpC5Sh5Ofy+xQOy8jo9fKEkn9gS8GxY4WA1ZfsMus+aWt3n+QuyZFkFd5dBy703R3Pl/SHN5mRdqBIvQR4dvXnQvRG79Ms7LMYv/WIQMAQIRhoTc21bwV9dxAqiPlkR+TBRaFA8AyTq3ZKtA3fIxfy84MJvVpXvwSYxJshrtdyPs984qtgEFkBl7ZwzHr+SLivGoAeXnK0knwfEiursNFlZpkSfqHLLmuVi2ulwVa8Kc4f9JRz07OJI1FW9Z2IJxkYxNM7oEqiiVBTViAHrgj7vM45Wt2xuXSFDgbKNPe9RzJK2VtIZkm07b6q3LKeq3TLT3ZWNeK3fT691k75KlpHOg0qNbejDLbzls="
    - secure: "hpmKfwrw4I3ATOf9LeFeZo8VaJs7uPqqT691l0u7B8+ARc8lBYMjedtE4+e5qyLC7x6dqgfoFZM0utsgPd+kis9LQ41bwFhlVYNS+NNfvCnzVSgkck0G8d8+Cpp3qwUC/pFOzcIuGv5mPYk7VxZKpfADl8rDtKeHWmQiaKPIEbGrwuQk4M6XFlAx44pMmuYPwHbGbga1pRgIpMUQXsXl1JJ6SQjBvE1xE3xkoaurET985AfPYXQTuRUxo+uanj6+NeOjhr9snLDelcL4sUMuJXdVPCxWEvuz6DJhHmcceFlUYUynqM6JZOP+iu0T+WQJZrUCODpcfFdfX0Kd6cP0AiMuS+tZyYavWECGZYd2fo7LrAow4ChuvVMFT3WQTbuR9milCZvl/6LCzFl3iStb7ixpu3YEX7WkVpVc3iUgYVi4i4IhEe+PDWUlaxyyTO3tqUfYQBGzrVlNPLByX6QxHTQ1lopQBDHD/QjpFI2zNs1K6cVptF0AKc9qJuSk8OOlUyCSsS67lUGHDsYSBtWeJzjAxmPrjkyFLbloJVskXmR5aXvxdjNLz+qU3IfSOsCJx8AP9WEREgFw2dzFnAlfTFWoc2vppKWN8v5VZPdcfKJRJRruki+61G5yVO7eKSn3yx8MTQTXWUaNMQe/N8c1VzbaNm9kIurTvicHZCmKscQ="

branches:
  except:
    - gh-pages

notifications:
  email: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
